name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack template
        shell: pwsh
        run: dotnet pack -o output
      - name: Upload template
        uses: actions/upload-artifact@v4
        if: matrix.image == 'ubuntu-latest'
        with:
          name: template
          path: output/*.nupkg

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Common preparation
      - name: Prepare build
        working-directory: content
        run: ./gradlew -PbuildConfiguration=Release prepare

      # Backend
      - name: Build Backend
        working-directory: content
        run: dotnet build -c Release

      # Plugin
      - name: Build
        working-directory: content
        run: ./gradlew -PbuildConfiguration=Release build
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}.test-results
          path: content/build/reports/tests
        if: ${{ always() }}
      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}.test-logs
          path: content/build/idea-sandbox/*/log-test
        if: ${{ always() }}

      # Distribution
      - name: Build Distribution
        if: matrix.image == 'ubuntu-latest'
        working-directory: content
        run: ./gradlew -PbuildConfiguration=Release :buildPlugin
      - name: Determine Version
        if: matrix.image == 'ubuntu-latest'
        shell: pwsh
        run: |
          $version = content/scripts/Get-Version.ps1
          "PLUGIN_VERSION=$version" | Out-File $env:GITHUB_ENV
      - name: Unpack Distribution # for the purpose of uploading
        if: matrix.image == 'ubuntu-latest'
        shell: pwsh
        run: content/scripts/Unpack-Distribution.ps1
      - name: Upload Distribution
        if: matrix.image == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: plugin-${{ env.PLUGIN_VERSION }}
          path: content/build/distributions/unpacked
